// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1yCf9DT1KcUqAHRO0oIglAjo4VUoKN74',
    appId: '1:414575648914:web:a967bf719909cc1cbac64b',
    messagingSenderId: '414575648914',
    projectId: 'speakeriot-64ab4',
    authDomain: 'speakeriot-64ab4.firebaseapp.com',
    storageBucket: 'speakeriot-64ab4.appspot.com',
    measurementId: 'G-G730CFWF9K',
    databaseURL:
        'https://speakeriot-64ab4-default-rtdb.asia-southeast1.firebasedatabase.app/',
  );

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyCYAC6bpRCTI0tMRAZOWIHFbL-6olQmtYU',
      appId: '1:414575648914:android:345da155b868ebc9bac64b',
      messagingSenderId: '414575648914',
      projectId: 'speakeriot-64ab4',
      storageBucket: 'speakeriot-64ab4.appspot.com',
      databaseURL:
          'https://speakeriot-64ab4-default-rtdb.asia-southeast1.firebasedatabase.app/');

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfFqlw07KbMckyhOab5qAGvOgnNu48UkM',
    appId: '1:414575648914:ios:5883981a6ce30a9cbac64b',
    messagingSenderId: '414575648914',
    projectId: 'speakeriot-64ab4',
    databaseURL:
        'https://speakeriot-64ab4-default-rtdb.asia-southeast1.firebasedatabase.app/',
    storageBucket: 'speakeriot-64ab4.appspot.com',
    iosClientId:
        '414575648914-hqsc9gc4ovk3ad55q5pl3p3hfmlf17jf.apps.googleusercontent.com',
    iosBundleId: 'com.example.speakeriot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfFqlw07KbMckyhOab5qAGvOgnNu48UkM',
    appId: '1:414575648914:ios:5883981a6ce30a9cbac64b',
    messagingSenderId: '414575648914',
    projectId: 'speakeriot-64ab4',
    databaseURL:
        'https://speakeriot-64ab4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'speakeriot-64ab4.appspot.com',
    iosClientId:
        '414575648914-hqsc9gc4ovk3ad55q5pl3p3hfmlf17jf.apps.googleusercontent.com',
    iosBundleId: 'com.example.speakeriot',
  );
}
